// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health/api": {
            "get": {
                "description": "簡単なヘルスチェック",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "API疎通確認",
                "responses": {}
            }
        },
        "/health/db-command": {
            "post": {
                "description": "簡単なヘルスチェック",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "API疎通確認",
                "parameters": [
                    {
                        "description": "リクエスト本文",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/health.DBCommandRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/health/db-query": {
            "get": {
                "description": "簡単なヘルスチェック",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "API疎通確認",
                "responses": {}
            }
        }
    },
    "definitions": {
        "health.DBCommandRequest": {
            "type": "object",
            "properties": {
                "text": {
                    "type": "string",
                    "example": "sample text"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "TemplateAPI.OnionArchitecture.Golang",
	Description:      "This is API Template for Onion Architecture.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
