version: '3.8'

services:
  api:
    build:
      context: ./API
      dockerfile: dockerfile
    container_name: api
    ports:
      - "8080:8080"
    environment:
      - DB_USER=root
      - DB_PASSWORD=yourpassword
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=appDB
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: appDB
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./DB/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
