version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appDB
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - ./MySQL/MySQL_data:/var/lib/mysql   # ← データディレクトリは空かDBデータだけ
      - ./MySQL/init.sql:/docker-entrypoint-initdb.d/init.sql  # ← 初期化SQLだけここにマウント
    ports:
      - "3306:3306"

  # swagger:
  #   build:
  #     context: ./Swagger
  #   ports:
  #     - "8081:80"  # ← ローカル8081をSwagger用コンテナの80番にマッピング
  #   volumes:
  #     - ./Swagger/docs:/usr/share/nginx/html:ro

volumes:
  db_data:
