root = "."
tmp_dir = "tmp"

[build]
  cmd = 'cmd /C "swag init --parseDependency --parseInternal && go build -o ./tmp/main.exe ."'
  bin = "tmp/main.exe"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["vendor"]
  exclude_file = ["*_test.go"]
  delay = 1000
  log = "stdout"

[log]
  color = true
  time = true

[run]
  watcher = "fsnotify"
