FROM golang:1.24.4

# 作業ディレクトリを設定
WORKDIR /app

# air をインストール（GOBIN に明示インストール）
ENV GOBIN=/go/bin
RUN go install github.com/air-verse/air@latest

# air 実行可能パスを PATH に追加
ENV PATH=$GOBIN:$PATH

# go module 関連の準備
COPY go.mod ./
COPY go.sum ./
RUN go mod download

# アプリケーションコードをコピー
COPY . .

# air コマンドで起動
CMD ["air"]
